# Generated by Django 5.2.1 on 2025-05-18 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_recipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.TextField(help_text='Каждый ингредиент с новой строки'),
        ),
    ]
